### ISSUE TITLE
distroless doesn't contain /bin/sh

### ISSUE THREAD

**Issue by chornlgscout** [kubernetes-csi/node-driver-registrar#81] opened 2020-05-11 22:39 UTC
Which makes this part of the readme example non-functional:
>                 command: ["/bin/sh", "-c", "rm -rf /registration/<plugin> /registration/<drivername.example.com>-reg.sock"]

**Comment by Madhu-1** [comment] 2020-05-12 05:46
this is duplicate of https://github.com/kubernetes-csi/node-driver-registrar/issues/56

**Closed** 2020-10-09 07:22 UTC
Labels: lifecycle/rotten
